---
schema: 4
parameters:
   RV: 0.25
   TLC: 4.0
   Acw: 8.0
   Bcw: -5.0
   Al: 3.0
   Bl: 0.2
   Dl: 10
   Kl: 0
   As: 4.0
   Bs: 0.5
   Ks: -0.5
   Vstar: 4.0
   Vcmax: 0.07
   Ac: 0.4
   Bc: 9.0
   Dc: 0.411
   Kc: 0.5
   Au: 2.0
   Ku: 8.0
   Rd: 18
   Cd: 0.2
   Rve: 1.0
   Cve: 0.5
   