---
schema: 2
elementsList:
- associatedFormula:
    id: Endo-tracheal Tube Resistance
    isTimeDependent: false
    isExternal: false
    formula: resistance1
    variables:
    - resistance1
  type: ResistorElm
  x: 0
  y: 1
  x1: 1 
  y1: 1
- associatedFormula:
    id: Tracheo-bronchial Resistance
    isTimeDependent: false
    isExternal: false
    formula: resistance2
    variables:
    - resistance2
  type: ResistorElm
  x: 1
  y: 1
  x1: 2 
  y1: 1
- associatedFormula:
    id: Lung Compliance
    isTimeDependent: false
    isExternal: false
    formula: capacitor1
    variables:
    - capacitor1
  type: CapacitorElm
  x: 2
  y: 1
  x1: 3 
  y1: 1
  showLeft: true
  idLeft: Alveoli
  showRight: true
  idRight: Intrathoracic Pressure
- associatedFormula:
    id: Chest wall compliance
    isTimeDependent: false
    isExternal: false
    formula: capacitor2
    variables:
    - capacitor2
  type: CapacitorElm
  x: 3
  y: 1
  x1: 4 
  y1: 1
- associatedFormula:
    id: Ventilator
    isTimeDependent: false
    isExternal: true
  type: ExternalVoltageElm
  x: 4
  y: 1
  x1: 0 
  y1: 1