---
schema: 5
elementsList:
- associatedFormula:
    id: Upper Airway Resistance
    isTimeDependent: false
    isExternal: false
    formula: resistanceU 
    variables:
    - resistanceU
  type: ResistorElm
  x: 0
  y: 0
  x1: 1 
  y1: 0
  showRight: true
  idRight: Alveoli
- associatedFormula:
    id: Lung Tissues Resistance
    isTimeDependent: false
    isExternal: false
    formula: resistanceL 
    variables:
    - resistanceL
  type: ResistorElm
  x: 1
  y: 0
  x1: 2 
  y1: 0
- associatedFormula:
    id: Lung Compliance
    isTimeDependent: true
    isExternal: false
    formula: capacitor
    variables:
    - capacitor
  type: CapacitorElm
  x: 2
  y: 0
  x1: 3
  y1: 0
- associatedFormula:
    id: Ventilator
    isTimeDependent: false
    isExternal: true
  type: ExternalVoltageElm
  x: 3
  y: 0
  x1: 0 
  y1: 0