---
schema: 6
elementsList:
- associatedFormula:
    id: Central Airways Resistance
    isTimeDependent: false
    isExternal: false
    formula: resistanceC
    variables:
    - resistanceC
  type: ResistorElm
  x: 0
  y: 2
  x1: 1 
  y1: 2
  showLeft: true
  idLeft: Airway Opening
  showRight: true
  idRight: Central Airways
- associatedFormula:
    id: Peripheral Airways Resistance
    isTimeDependent: false
    isExternal: false
    formula: resistanceP
    variables:
    - resistanceP
  type: ResistorElm
  x: 1
  y: 2
  x1: 2 
  y1: 2
- associatedFormula:
    id: Shunt Compliance
    isTimeDependent: false
    isExternal: false
    formula: capacitorS
    variables:
    - capacitorS
  type: CapacitorElm
  x: 1
  y: 2
  x1: 1
  y1: 0
- associatedFormula:
    id: Lung Compliance
    isTimeDependent: false
    isExternal: false
    formula: capacitorL
    variables:
    - capacitorL
  type: CapacitorElm
  x: 2
  y: 2
  x1: 2
  y1: 1
  showLeft: true
  idLeft: Alveoli
  showRight: true
  idRight: Pleural Pressure
- associatedFormula:
    id: Chest wall Compliance
    isTimeDependent: false
    isExternal: false
    formula: capacitorW
    variables:
    - capacitorW
  type: CapacitorElm
  x: 2
  y: 1
  x1: 1
  y1: 0
- associatedFormula:
    id: Ventilator
    isTimeDependent: false
    isExternal: true
  type: ExternalVoltageElm
  x: 1
  y: 0
  x1: 0 
  y1: 2