---
schema: 3
elementsList:
- elementName: Mouth to Larynx Resistance
  associatedFormula:
    isTimeDependent: false
    isExternal: false
    formula: resistanceMl
    variables:
    - resistanceMl
  type: ResistorElm
  x: 0
  y: 2
  x1: 1 
  y1: 2
  showLeft: true
  idLeft: Airway Opening
  showRight: true
  idRight: Larynx
- elementName: Larynx to Trachea Resistance
  associatedFormula: 
    isTimeDependent: false
    isExternal: false
    formula: resistanceLt
    variables:
    - resistanceLt
  type: ResistorElm
  x: 1
  y: 2
  x1: 2 
  y1: 2
  showRight: true
  idRight: Trachea
- elementName: Trachea to Bronchea Resistance
  associatedFormula:
    isTimeDependent: false
    isExternal: false
    formula: resistanceTb
    variables:
    - resistanceTb
  type: ResistorElm
  x: 2
  y: 2
  x1: 3 
  y1: 2
  showRight: true
  idRight: Bronchea
- elementName: Bronchea to Alveoli Resistance
  associatedFormula:
    isTimeDependent: false
    isExternal: false
    formula: resistanceBa
    variables:
    - resistanceBa
  type: ResistorElm
  x: 3
  y: 2
  x1: 4 
  y1: 2
  showRight: true
  idRight: Alveoli
- elementName: Larinx Capacitance
  associatedFormula:
    isTimeDependent: false
    isExternal: false
    formula: capacitorL
    variables:
    - capacitorL
  type: CapacitorElm
  x: 1
  y: 2
  x1: 1 
  y1: 0
- elementName: Trachea Capacitance
  associatedFormula:
    isTimeDependent: false
    isExternal: false
    formula: capacitorTr
    variables:
    - capacitorTr
  type: CapacitorElm
  x: 2
  y: 2
  x1: 3 
  y1: 1
- elementName: Bronchea Capacitance
  associatedFormula:
    isTimeDependent: false
    isExternal: false
    formula: capacitorB
    variables:
    - capacitorB
  type: CapacitorElm
  x: 3
  y: 2
  x1: 3 
  y1: 1
  showRight: true
  idRight: Pleural Space
- elementName: Alveoli Capacitance
  associatedFormula:
    isTimeDependent: false
    isExternal: false
    formula: capacitorA
    variables:
    - capacitorA
  type: CapacitorElm
  x: 4
  y: 2
  x1: 3 
  y1: 1
- elementName: Chest wall Capacitance
  associatedFormula:
    isTimeDependent: false
    isExternal: false
    formula: capacitorCw
    variables:
    - capacitorCw
  type: CapacitorElm
  x: 3
  y: 1
  x1: 1 
  y1: 0  
- elementName: Ventilator
  associatedFormula:
    isTimeDependent: false
    isExternal: true
  type: ExternalVoltageElm
  x: 1
  y: 0
  x1: 0 
  y1: 2