---
schema: 1
elementsList:
- associatedFormula:
    id: R1
    isTimeDependent: false
    isExternal: false
    formula: resistance1
    variables:
    - resistance1
  type: ResistorElm
  x: 0
  y: 0
  x1: 1 
  y1: 0
- associatedFormula:
    id: C1
    isTimeDependent: false
    isExternal: false
    formula: capacitor1
    variables:
    - capacitor1
  type: CapacitorElm
  x: 1
  y: 0
  x1: 2 
  y1: 0
- associatedFormula:
    id: Ventilator
    isTimeDependent: false
    isExternal: true
  type: ExternalVoltageElm
  x: 2
  y: 0
  x1: 0 
  y1: 0