---
schema: 3
elementsList:
- associatedFormula:
    id: Mouth to Larinx Resistance
    isTimeDependent: false
    isExternal: false
    formula: resistanceMl
    variables:
    - resistanceMl
  type: ResistorElm
  x: 0
  y: 2
  x1: 1 
  y1: 2
- associatedFormula:
    id: Larinx to Trachea Resistance 
    isTimeDependent: false
    isExternal: false
    formula: resistanceLt
    variables:
    - resistanceLt
  type: ResistorElm
  x: 1
  y: 2
  x1: 2 
  y1: 2
- associatedFormula:
    id: Trachea to Bronchea Resistance
    isTimeDependent: false
    isExternal: false
    formula: resistanceTb
    variables:
    - resistanceTb
  type: ResistorElm
  x: 2
  y: 2
  x1: 3 
  y1: 2
- associatedFormula:
    id: Bronchea to Alveoli Resistance
    isTimeDependent: false
    isExternal: false
    formula: resistanceBa
    variables:
    - resistanceBa
  type: ResistorElm
  x: 3
  y: 2
  x1: 4 
  y1: 2
- associatedFormula:
    id: Larinx Capacitance
    isTimeDependent: false
    isExternal: false
    formula: capacitorL
    variables:
    - capacitorL
  type: CapacitorElm
  x: 1
  y: 2
  x1: 1 
  y1: 0
- associatedFormula:
    id: Trachea Capacitance
    isTimeDependent: false
    isExternal: false
    formula: capacitorTr
    variables:
    - capacitorTr
  type: CapacitorElm
  x: 2
  y: 2
  x1: 3 
  y1: 1
- associatedFormula:
    id: Bronchea Capacitance
    isTimeDependent: false
    isExternal: false
    formula: capacitorB
    variables:
    - capacitorB
  type: CapacitorElm
  x: 3
  y: 2
  x1: 3 
  y1: 1
- associatedFormula:
    id: Alveoli Capacitance
    isTimeDependent: false
    isExternal: false
    formula: capacitorA
    variables:
    - capacitorA
  type: CapacitorElm
  x: 4
  y: 2
  x1: 3 
  y1: 1
- associatedFormula:
    id: Chest wall Capacitance
    isTimeDependent: false
    isExternal: false
    formula: capacitorCw
    variables:
    - capacitorCw
  type: CapacitorElm
  x: 3
  y: 1
  x1: 1 
  y1: 0  
- associatedFormula:
    id: Ventilator
    isTimeDependent: false
    isExternal: true
  type: ExternalVoltageElm
  x: 1
  y: 0
  x1: 0 
  y1: 2