---
schema: 6
elementsList:
- associatedFormula:
    id: Rc
    isTimeDependent: false
    isExternal: false
    formula: resistanceC
    variables:
    - resistanceC
  type: ResistorElm
  x: 0
  y: 2
  x1: 1 
  y1: 2
- associatedFormula:
    id: Rp
    isTimeDependent: false
    isExternal: false
    formula: resistanceP
    variables:
    - resistanceP
  type: ResistorElm
  x: 1
  y: 2
  x1: 2 
  y1: 2
- associatedFormula:
    id: Cs
    isTimeDependent: false
    isExternal: false
    formula: capacitorS
    variables:
    - capacitorS
  type: CapacitorElm
  x: 1
  y: 2
  x1: 1
  y1: 0
- associatedFormula:
    id: Cl
    isTimeDependent: false
    isExternal: false
    formula: capacitorL
    variables:
    - capacitorL
  type: CapacitorElm
  x: 2
  y: 2
  x1: 2
  y1: 1
- associatedFormula:
    id: Cw
    isTimeDependent: false
    isExternal: false
    formula: capacitorW
    variables:
    - capacitorW
  type: CapacitorElm
  x: 2
  y: 1
  x1: 1
  y1: 0
- associatedFormula:
    id: Ventilator
    isTimeDependent: false
    isExternal: true
  type: ExternalVoltageElm
  x: 1
  y: 0
  x1: 0 
  y1: 2