---
schema: 4
elementsList:
- id: Upper airway resistance
  formula: Au + Ku * ABS(Vcw(dt))
  variables:
  - Au
  - Ku
  - Vcw
  - dt
  type: ResistorElm
  x: 1
  y: 6
  x1: 1 
  y1: 7
- id: Collapsible airway resistance
  formula: Kc * (1 + e^(-Ac*(Pt-Bc)))^(2*Dc)
  variables:
  - Kc
  - Ac
  - Pt
  - Bc
  - Dc
  type: ResistorElm
  x: 1
  y: 5
  x1: 1 
  y1: 6
- id: Smaller airway resistance
  formula: As * e^(Ks * (Vl - RV)/(Vstar - RV)) + Bs
  variables:
  - As
  - Ks
  - Vl
  - RV
  - Vstar
  - Bs
  type: ResistorElm
  x: 1
  y: 4
  x1: 1 
  y1: 5
- id: Rve
  formula: resistanceVE
  variables:
  - resistanceVE
  type: ResistorElm
  x: 1
  y: 1
  x1: 1 
  y1: 2
- id: Rd
  formula: resistanceD
  variables:
  - resistanceD
  type: ResistorElm
  x: 0
  y: 2
  x1: 0 
  y1: 3
- id: Collapsible airway capacitance
  formula: Vcmax / (1 + e^(-Ac*(Pt-Bc)))^Dc
  variables:
  - Vcmax
  - Ac
  - Pt
  - Bc
  - Dc
  type: CapacitorElm
  x: 1
  y: 3
  x1: 1 
  y1: 5
- id: Current lung volume
  formula: Al / (1 + e^(-Bl*(Pt-Dl)))
  variables:
  - Al
  - Bl
  - Pt
  - Dl
  type: CapacitorElm
  x: 1
  y: 3
  x1: 1 
  y1: 4
- id: Current chest volume
  formula: ((TLC - RV)/(0.99 + e^(-(Pcw-Acw)/Bcw))) + RV
  variables:
  - TLC
  - RV
  - Pcw
  - Acw
  - Bcw
  type: CapacitorElm
  x: 1
  y: 2
  x1: 1 
  y1: 3
- id: Cve
  formula: capacitorVE
  variables:
  - capacitorVE
  type: CapacitorElm
  x: 1
  y: 1
  x1: 1 
  y1: 2
- id: Pmus
  formula: 
  variables:
  type: ACVoltageElm
  x: 1
  y: 0
  x1: 1 
  y1: 1
- id: PipPEEP
  formula: 
  variables:
  type: DCVoltageElm
  x: 0
  y: 0
  x1: 0 
  y1: 2