################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CPP_SRCS += \
../libzmq/src/address.cpp \
../libzmq/src/channel.cpp \
../libzmq/src/client.cpp \
../libzmq/src/clock.cpp \
../libzmq/src/ctx.cpp \
../libzmq/src/curve_client.cpp \
../libzmq/src/curve_mechanism_base.cpp \
../libzmq/src/curve_server.cpp \
../libzmq/src/dealer.cpp \
../libzmq/src/decoder_allocators.cpp \
../libzmq/src/devpoll.cpp \
../libzmq/src/dgram.cpp \
../libzmq/src/dish.cpp \
../libzmq/src/dist.cpp \
../libzmq/src/endpoint.cpp \
../libzmq/src/epoll.cpp \
../libzmq/src/err.cpp \
../libzmq/src/fq.cpp \
../libzmq/src/gather.cpp \
../libzmq/src/gssapi_client.cpp \
../libzmq/src/gssapi_mechanism_base.cpp \
../libzmq/src/gssapi_server.cpp \
../libzmq/src/io_object.cpp \
../libzmq/src/io_thread.cpp \
../libzmq/src/ip.cpp \
../libzmq/src/ip_resolver.cpp \
../libzmq/src/ipc_address.cpp \
../libzmq/src/ipc_connecter.cpp \
../libzmq/src/ipc_listener.cpp \
../libzmq/src/kqueue.cpp \
../libzmq/src/lb.cpp \
../libzmq/src/mailbox.cpp \
../libzmq/src/mailbox_safe.cpp \
../libzmq/src/mechanism.cpp \
../libzmq/src/mechanism_base.cpp \
../libzmq/src/metadata.cpp \
../libzmq/src/msg.cpp \
../libzmq/src/mtrie.cpp \
../libzmq/src/norm_engine.cpp \
../libzmq/src/null_mechanism.cpp \
../libzmq/src/object.cpp \
../libzmq/src/options.cpp \
../libzmq/src/own.cpp \
../libzmq/src/pair.cpp \
../libzmq/src/peer.cpp \
../libzmq/src/pgm_receiver.cpp \
../libzmq/src/pgm_sender.cpp \
../libzmq/src/pgm_socket.cpp \
../libzmq/src/pipe.cpp \
../libzmq/src/plain_client.cpp \
../libzmq/src/plain_server.cpp \
../libzmq/src/poll.cpp \
../libzmq/src/poller_base.cpp \
../libzmq/src/polling_util.cpp \
../libzmq/src/pollset.cpp \
../libzmq/src/precompiled.cpp \
../libzmq/src/proxy.cpp \
../libzmq/src/pub.cpp \
../libzmq/src/pull.cpp \
../libzmq/src/push.cpp \
../libzmq/src/radio.cpp \
../libzmq/src/radix_tree.cpp \
../libzmq/src/random.cpp \
../libzmq/src/raw_decoder.cpp \
../libzmq/src/raw_encoder.cpp \
../libzmq/src/raw_engine.cpp \
../libzmq/src/reaper.cpp \
../libzmq/src/rep.cpp \
../libzmq/src/req.cpp \
../libzmq/src/router.cpp \
../libzmq/src/scatter.cpp \
../libzmq/src/select.cpp \
../libzmq/src/server.cpp \
../libzmq/src/session_base.cpp \
../libzmq/src/signaler.cpp \
../libzmq/src/socket_base.cpp \
../libzmq/src/socket_poller.cpp \
../libzmq/src/socks.cpp \
../libzmq/src/socks_connecter.cpp \
../libzmq/src/stream.cpp \
../libzmq/src/stream_connecter_base.cpp \
../libzmq/src/stream_engine_base.cpp \
../libzmq/src/stream_listener_base.cpp \
../libzmq/src/sub.cpp \
../libzmq/src/tcp.cpp \
../libzmq/src/tcp_address.cpp \
../libzmq/src/tcp_connecter.cpp \
../libzmq/src/tcp_listener.cpp \
../libzmq/src/thread.cpp \
../libzmq/src/timers.cpp \
../libzmq/src/tipc_address.cpp \
../libzmq/src/tipc_connecter.cpp \
../libzmq/src/tipc_listener.cpp \
../libzmq/src/trie.cpp \
../libzmq/src/udp_address.cpp \
../libzmq/src/udp_engine.cpp \
../libzmq/src/v1_decoder.cpp \
../libzmq/src/v1_encoder.cpp \
../libzmq/src/v2_decoder.cpp \
../libzmq/src/v2_encoder.cpp \
../libzmq/src/v3_1_encoder.cpp \
../libzmq/src/vmci.cpp \
../libzmq/src/vmci_address.cpp \
../libzmq/src/vmci_connecter.cpp \
../libzmq/src/vmci_listener.cpp \
../libzmq/src/ws_address.cpp \
../libzmq/src/ws_connecter.cpp \
../libzmq/src/ws_decoder.cpp \
../libzmq/src/ws_encoder.cpp \
../libzmq/src/ws_engine.cpp \
../libzmq/src/ws_listener.cpp \
../libzmq/src/wss_address.cpp \
../libzmq/src/wss_engine.cpp \
../libzmq/src/xpub.cpp \
../libzmq/src/xsub.cpp \
../libzmq/src/zap_client.cpp \
../libzmq/src/zmq.cpp \
../libzmq/src/zmq_utils.cpp \
../libzmq/src/zmtp_engine.cpp 

C_SRCS += \
../libzmq/src/tweetnacl.c 

OBJS += \
./libzmq/src/address.o \
./libzmq/src/channel.o \
./libzmq/src/client.o \
./libzmq/src/clock.o \
./libzmq/src/ctx.o \
./libzmq/src/curve_client.o \
./libzmq/src/curve_mechanism_base.o \
./libzmq/src/curve_server.o \
./libzmq/src/dealer.o \
./libzmq/src/decoder_allocators.o \
./libzmq/src/devpoll.o \
./libzmq/src/dgram.o \
./libzmq/src/dish.o \
./libzmq/src/dist.o \
./libzmq/src/endpoint.o \
./libzmq/src/epoll.o \
./libzmq/src/err.o \
./libzmq/src/fq.o \
./libzmq/src/gather.o \
./libzmq/src/gssapi_client.o \
./libzmq/src/gssapi_mechanism_base.o \
./libzmq/src/gssapi_server.o \
./libzmq/src/io_object.o \
./libzmq/src/io_thread.o \
./libzmq/src/ip.o \
./libzmq/src/ip_resolver.o \
./libzmq/src/ipc_address.o \
./libzmq/src/ipc_connecter.o \
./libzmq/src/ipc_listener.o \
./libzmq/src/kqueue.o \
./libzmq/src/lb.o \
./libzmq/src/mailbox.o \
./libzmq/src/mailbox_safe.o \
./libzmq/src/mechanism.o \
./libzmq/src/mechanism_base.o \
./libzmq/src/metadata.o \
./libzmq/src/msg.o \
./libzmq/src/mtrie.o \
./libzmq/src/norm_engine.o \
./libzmq/src/null_mechanism.o \
./libzmq/src/object.o \
./libzmq/src/options.o \
./libzmq/src/own.o \
./libzmq/src/pair.o \
./libzmq/src/peer.o \
./libzmq/src/pgm_receiver.o \
./libzmq/src/pgm_sender.o \
./libzmq/src/pgm_socket.o \
./libzmq/src/pipe.o \
./libzmq/src/plain_client.o \
./libzmq/src/plain_server.o \
./libzmq/src/poll.o \
./libzmq/src/poller_base.o \
./libzmq/src/polling_util.o \
./libzmq/src/pollset.o \
./libzmq/src/precompiled.o \
./libzmq/src/proxy.o \
./libzmq/src/pub.o \
./libzmq/src/pull.o \
./libzmq/src/push.o \
./libzmq/src/radio.o \
./libzmq/src/radix_tree.o \
./libzmq/src/random.o \
./libzmq/src/raw_decoder.o \
./libzmq/src/raw_encoder.o \
./libzmq/src/raw_engine.o \
./libzmq/src/reaper.o \
./libzmq/src/rep.o \
./libzmq/src/req.o \
./libzmq/src/router.o \
./libzmq/src/scatter.o \
./libzmq/src/select.o \
./libzmq/src/server.o \
./libzmq/src/session_base.o \
./libzmq/src/signaler.o \
./libzmq/src/socket_base.o \
./libzmq/src/socket_poller.o \
./libzmq/src/socks.o \
./libzmq/src/socks_connecter.o \
./libzmq/src/stream.o \
./libzmq/src/stream_connecter_base.o \
./libzmq/src/stream_engine_base.o \
./libzmq/src/stream_listener_base.o \
./libzmq/src/sub.o \
./libzmq/src/tcp.o \
./libzmq/src/tcp_address.o \
./libzmq/src/tcp_connecter.o \
./libzmq/src/tcp_listener.o \
./libzmq/src/thread.o \
./libzmq/src/timers.o \
./libzmq/src/tipc_address.o \
./libzmq/src/tipc_connecter.o \
./libzmq/src/tipc_listener.o \
./libzmq/src/trie.o \
./libzmq/src/tweetnacl.o \
./libzmq/src/udp_address.o \
./libzmq/src/udp_engine.o \
./libzmq/src/v1_decoder.o \
./libzmq/src/v1_encoder.o \
./libzmq/src/v2_decoder.o \
./libzmq/src/v2_encoder.o \
./libzmq/src/v3_1_encoder.o \
./libzmq/src/vmci.o \
./libzmq/src/vmci_address.o \
./libzmq/src/vmci_connecter.o \
./libzmq/src/vmci_listener.o \
./libzmq/src/ws_address.o \
./libzmq/src/ws_connecter.o \
./libzmq/src/ws_decoder.o \
./libzmq/src/ws_encoder.o \
./libzmq/src/ws_engine.o \
./libzmq/src/ws_listener.o \
./libzmq/src/wss_address.o \
./libzmq/src/wss_engine.o \
./libzmq/src/xpub.o \
./libzmq/src/xsub.o \
./libzmq/src/zap_client.o \
./libzmq/src/zmq.o \
./libzmq/src/zmq_utils.o \
./libzmq/src/zmtp_engine.o 

CPP_DEPS += \
./libzmq/src/address.d \
./libzmq/src/channel.d \
./libzmq/src/client.d \
./libzmq/src/clock.d \
./libzmq/src/ctx.d \
./libzmq/src/curve_client.d \
./libzmq/src/curve_mechanism_base.d \
./libzmq/src/curve_server.d \
./libzmq/src/dealer.d \
./libzmq/src/decoder_allocators.d \
./libzmq/src/devpoll.d \
./libzmq/src/dgram.d \
./libzmq/src/dish.d \
./libzmq/src/dist.d \
./libzmq/src/endpoint.d \
./libzmq/src/epoll.d \
./libzmq/src/err.d \
./libzmq/src/fq.d \
./libzmq/src/gather.d \
./libzmq/src/gssapi_client.d \
./libzmq/src/gssapi_mechanism_base.d \
./libzmq/src/gssapi_server.d \
./libzmq/src/io_object.d \
./libzmq/src/io_thread.d \
./libzmq/src/ip.d \
./libzmq/src/ip_resolver.d \
./libzmq/src/ipc_address.d \
./libzmq/src/ipc_connecter.d \
./libzmq/src/ipc_listener.d \
./libzmq/src/kqueue.d \
./libzmq/src/lb.d \
./libzmq/src/mailbox.d \
./libzmq/src/mailbox_safe.d \
./libzmq/src/mechanism.d \
./libzmq/src/mechanism_base.d \
./libzmq/src/metadata.d \
./libzmq/src/msg.d \
./libzmq/src/mtrie.d \
./libzmq/src/norm_engine.d \
./libzmq/src/null_mechanism.d \
./libzmq/src/object.d \
./libzmq/src/options.d \
./libzmq/src/own.d \
./libzmq/src/pair.d \
./libzmq/src/peer.d \
./libzmq/src/pgm_receiver.d \
./libzmq/src/pgm_sender.d \
./libzmq/src/pgm_socket.d \
./libzmq/src/pipe.d \
./libzmq/src/plain_client.d \
./libzmq/src/plain_server.d \
./libzmq/src/poll.d \
./libzmq/src/poller_base.d \
./libzmq/src/polling_util.d \
./libzmq/src/pollset.d \
./libzmq/src/precompiled.d \
./libzmq/src/proxy.d \
./libzmq/src/pub.d \
./libzmq/src/pull.d \
./libzmq/src/push.d \
./libzmq/src/radio.d \
./libzmq/src/radix_tree.d \
./libzmq/src/random.d \
./libzmq/src/raw_decoder.d \
./libzmq/src/raw_encoder.d \
./libzmq/src/raw_engine.d \
./libzmq/src/reaper.d \
./libzmq/src/rep.d \
./libzmq/src/req.d \
./libzmq/src/router.d \
./libzmq/src/scatter.d \
./libzmq/src/select.d \
./libzmq/src/server.d \
./libzmq/src/session_base.d \
./libzmq/src/signaler.d \
./libzmq/src/socket_base.d \
./libzmq/src/socket_poller.d \
./libzmq/src/socks.d \
./libzmq/src/socks_connecter.d \
./libzmq/src/stream.d \
./libzmq/src/stream_connecter_base.d \
./libzmq/src/stream_engine_base.d \
./libzmq/src/stream_listener_base.d \
./libzmq/src/sub.d \
./libzmq/src/tcp.d \
./libzmq/src/tcp_address.d \
./libzmq/src/tcp_connecter.d \
./libzmq/src/tcp_listener.d \
./libzmq/src/thread.d \
./libzmq/src/timers.d \
./libzmq/src/tipc_address.d \
./libzmq/src/tipc_connecter.d \
./libzmq/src/tipc_listener.d \
./libzmq/src/trie.d \
./libzmq/src/udp_address.d \
./libzmq/src/udp_engine.d \
./libzmq/src/v1_decoder.d \
./libzmq/src/v1_encoder.d \
./libzmq/src/v2_decoder.d \
./libzmq/src/v2_encoder.d \
./libzmq/src/v3_1_encoder.d \
./libzmq/src/vmci.d \
./libzmq/src/vmci_address.d \
./libzmq/src/vmci_connecter.d \
./libzmq/src/vmci_listener.d \
./libzmq/src/ws_address.d \
./libzmq/src/ws_connecter.d \
./libzmq/src/ws_decoder.d \
./libzmq/src/ws_encoder.d \
./libzmq/src/ws_engine.d \
./libzmq/src/ws_listener.d \
./libzmq/src/wss_address.d \
./libzmq/src/wss_engine.d \
./libzmq/src/xpub.d \
./libzmq/src/xsub.d \
./libzmq/src/zap_client.d \
./libzmq/src/zmq.d \
./libzmq/src/zmq_utils.d \
./libzmq/src/zmtp_engine.d 

C_DEPS += \
./libzmq/src/tweetnacl.d 


# Each subdirectory must supply rules for building sources it contributes
libzmq/src/%.o: ../libzmq/src/%.cpp
	@echo 'Building file: $<'
	@echo 'Invoking: Cygwin C++ Compiler'
	g++ -DZMQ_USE_SELECT -DZMQ_IOTHREAD_POLLER_USE_SELECT -DZMQ_POLL_BASED_ON_SELECT -I"F:\Repository MVM\mvm-adapt\zeromqexamples\client_vent\zmq" -I"F:\Repository MVM\mvm-adapt\zeromqexamples\client_vent\libzmq" -I"F:\Repository MVM\mvm-adapt\zeromqexamples\client_vent\libzmq\include" -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

libzmq/src/%.o: ../libzmq/src/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cygwin C Compiler'
	gcc -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


